run_type = "sampling"
device = "cpu"
json_out_config = "results/metrics/03_sanity_sampling_config.json"

[parameters]

model_file = "external/REINVENT4/priors/reinvent.prior"
sample_strategy = "multinomial"
temperature = 1.0

output_file = "data/generated/reinvent_sanity_100.csv"

num_smiles = 100
unique_molecules = true
randomize_smiles = true
